### ISSUE TITLE
Does piano midi also work?

### ISSUE THREAD

**Issue by sukun1045** [bwang514/PerformanceNet#2]
Hi guys, nice work. In the paper you tried the cello, violin and flute data and I plan to train it on piano midi data, have you guys tried that before? If so, what are the differences compared to other instruments? More specifically, 1) How many minutes of training data does piano need? (In paper you use different duration for different instruments). 2) What are the overlaps between chunks used in piano data? 3) Have you guys tried on shorter clips (like 2-second instead of 5-second) and would it easier to train? 4) Is high sampling rate (44.1k) necessary to get reasonable audio output?

Look forward to your replies. Thank you.

**Comment by bwang514** [comment]
HI @sukun1045, we did try piano before using the setup identical to other instruments and it worked decently.

**Comment by sukun1045** [comment]
Thanks for your reply. I did succeed implementing the piano version. Just to ask one more technical detail that is not in the code. Since the output is about 2 seconds. And I notice the samples on YouTube is longer. How do you concatenate multiple 2 seconds audio together? I realize if I directly concatenate generated audio segments together, some discontinuities may happen. Is there a smart way to do that?

**Comment by bwang514** [comment]
Hi @sukun1045 , sorry for the late reply! Since the model is fully-convolutional I believe the length of the output is variable, depending on your input. But I guess you've solved this problem on your own since I saw your paper on arxiv. Nice work!
